# python-level-5-numpy-module

Use the "Run" button to execute the code.

In [15]:
!pip install jovian --upgrade --quiet

In [16]:
import jovian

<IPython.core.display.Javascript object>

In [63]:
# Execute this to save new versions of the notebook
jovian.commit(project="python-level-5-numpy-module")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "asad-cuet/python-level-5-numpy-module" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/asad-cuet/python-level-5-numpy-module


'https://jovian.ai/asad-cuet/python-level-5-numpy-module'

# Numpy Array
### Numpy array is not as python list.You need to convert list to numpy array by calling numpy module


In [2]:
import numpy as np


In [3]:
list=[1,2,3,]
numpy_array=np.array(list)
print(numpy_array)

[1 2 3]


In [4]:
type(numpy_array)

numpy.ndarray

In [5]:
numpy_array[0]

1

### Lets do a problem solve.Dot-product

In [9]:
list1=[1,2,3]
list2=[9,8,7]

#now we will do multiply same index value and then get summission of them

result=0
for x,y in zip(list1,list2):
    result+=x*y
    
print(result)     #this is called dot-product of two vector.Two vector means 2 list
    

46


### Dot-product by numpy

In [20]:
list1=np.array(list1)
list2=np.array(list2)
result=np.dot(list1,list2)  #to see doc. of dot() run:help(np.dot)
print(result)

46


In [25]:
tup=tuple(range(1,10))
print(tup)
#lis=list(tup)
#print(list)

(1, 2, 3, 4, 5, 6, 7, 8, 9)


In [41]:
%%time
#again
list1=tuple(range(0,1000))   #equal length
list2=tuple(range(1000,2000))
list1_np=np.array(list1)
list2_np=np.array(list2)

result=np.dot(list1_np,list2_np)
print(result)

832333500
CPU times: user 272 µs, sys: 56 µs, total: 328 µs
Wall time: 290 µs


# Multi-dimensional Numpy array

### 2D

In [45]:
list=[[1,2,3],     # 2D
      [5,6,7],
      [10,11,12]]
print(list)

list_np=np.array(list)
print(list_np)

[[1, 2, 3], [5, 6, 7], [10, 11, 12]]
[[ 1  2  3]
 [ 5  6  7]
 [10 11 12]]


### Array Dimension

In [47]:
print(list_np.shape)

(3, 3)


### 3D array

In [62]:
list=[
    [
        [1,2,3],[4,5,6]
    ],
    [
        [10,11,12],[13,14,15]
    ]
]
print(list)

list_np=np.array(list)
print('Dimension:',list_np.shape)   #shape only for numpy
print(list_np)

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]]]
Dimension: (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]


### Array value type


In [63]:
list_np.dtype    #dtype only for numpy

dtype('int64')

### Reshape array or change dimension

In [98]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr,'shape:',arr.shape)

newarr = arr.reshape(4, 3)

print(newarr,'shape:',newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12] shape: (12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] shape: (4, 3)


### Dot product in matrix or Matrix multiplication

In [67]:
climate_data=[     # 4x3
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]
weights=[1,2,3]   #3x1
climate_data_np=np.array(climate_data)
weights_np=np.array(weights)

print('Dimension:',climate_data_np.shape,'and',weights_np.shape)

#method
res=np.matmul(climate_data_np,weights_np)

print(res,'and dimension:',res.shape)

Dimension: (4, 3) and (3,)
[14 32 50 68] and dimension: (4,)


In [69]:
#at. multiplication also can do by:

climate_data_np @ weights_np

array([14, 32, 50, 68])

# CSV data files

### Download a .txt file

In [71]:
import urllib.request as url

url.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')  #2nd parameter is name of downloaded file

#go to file>open>climate.txt

('climate.txt', <http.client.HTTPMessage at 0x7fccdd06e280>)

### Retrive data in variavle from .txt file

In [75]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)  #delimiter is sperator of data.which is coma

print(climate_data,'Shape:',climate_data.shape)

[[25. 76. 99.]
 [39. 65. 70.]
 [59. 45. 77.]
 ...
 [99. 62. 58.]
 [70. 71. 91.]
 [92. 39. 76.]] Shape: (10000, 3)


### dot product

In [76]:
weights=np.array([0.3,0.2,0.5])
climate_data @ weights

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

### Putting value in array from another array

In [89]:
result = climate_data @ weights
print(result,'shape:',result.shape)

[72.2 59.7 65.2 ... 71.1 80.7 73.4] shape: (10000,)


##### Since we wish to add new columns, we pass the argument axis=1 to np.concatenate. The axis argument specifies the dimension for concatenation.

#####  We use the np.reshape function to change the shape of yields from (10000,) to (10000,1)

In [88]:
climate_result=np.concatenate((climate_data,result.reshape(10000,1)),axis=1)
print(climate_result)

[[25.  76.  99.  72.2]
 [39.  65.  70.  59.7]
 [59.  45.  77.  65.2]
 ...
 [99.  62.  58.  71.1]
 [70.  71.  91.  80.7]
 [92.  39.  76.  73.4]]


### Saving array in a .txt file 

In [94]:
np.savetxt(
      'climate_result.txt',   #file name
       climate_result,        #the array
      fmt='%.2f',
      delimiter=',',
      header='temperature,rainfall,humidity,yeild_apples',
      comments=''
)
#if run code again,file replace

# Numpy function reference:


In [101]:
""""
##### https://jovian.ai/outlink?url=https%3A%2F%2Fnumpy.org%2Fdoc%2Fstable%2Freference%2Froutines.html

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:

Mathematics: np.sum, np.exp, np.round, arithemtic operators
Array manipulation: np.reshape, np.stack, np.concatenate, np.split
Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
Statistics: np.mean, np.median, np.std, np.max


""""

SyntaxError: EOL while scanning string literal (1889298008.py, line 12)

# Arithmetic operation

In [5]:
import numpy as np
arr1=[[1,2,3],
      [4,5,6],
      [7,8,9]]
arr2=[[10,11,12],
      [13,14,15],
      [16,17,18]]
arr1=np.array(arr1)
arr2=np.array(arr2)

In [6]:
arr1+arr2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [7]:
arr1-arr2

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [8]:
arr1*arr2

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [9]:
arr1 @ arr2

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [10]:
arr1+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
arr1*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
arr1/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [13]:
arr1%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

## Beoadcasting

In [18]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr3=[1,1,1]
arr3=np.array(arr3)

In [20]:
arr3

array([1, 1, 1])

In [22]:
arr1+arr3  #arr3 will convert to 3x3 by repeated the row.It's called broadcasting

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# Comparison operation

In [23]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
arr1 == arr2  #result is array of boolen

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [26]:
arr1>arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [27]:
arr1<arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [29]:
arr1!=arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [31]:
(arr1==arr2).sum()  #True=1,False=0.Sum is number of mathced elements

0

# Numpy Array Indexing

In [32]:
arr=[
    [[1,2,3],
     [4,5,6]],
    
    [[9,8,7],
     [6,5,4]],
    
    [[10,11,12],
     [13,14,15]]
]
arr=np.array(arr)

In [33]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9,  8,  7],
        [ 6,  5,  4]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [34]:
arr.shape

(3, 2, 3)

In [35]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr[1]

array([[9, 8, 7],
       [6, 5, 4]])

In [37]:
arr[2]

array([[10, 11, 12],
       [13, 14, 15]])

In [38]:
arr[1,0]

array([9, 8, 7])

In [39]:
arr[1,0,2]

7

## Range index

In [41]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9,  8,  7],
        [ 6,  5,  4]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [42]:
arr[1:] #1:  >empty means to the end

array([[[ 9,  8,  7],
        [ 6,  5,  4]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [44]:
arr[:1] # :1 means 0:1  [a:b] means a to b-1

array([[[1, 2, 3],
        [4, 5, 6]]])

In [58]:
arr[1:,0:1]

array([[[ 9,  8,  7],
        [ 6,  5,  4]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [59]:
arr[1:,0:1,0]

array([[ 9],
       [10]])

In [62]:
arr[1:,0:1,1]

array([[ 8],
       [11]])

In [60]:
arr[1:,0:]

array([[[ 9,  8,  7],
        [ 6,  5,  4]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [61]:
arr[1:,0:,0]

array([[ 9,  6],
       [10, 13]])

# Make array by function

In [64]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
np.eye(3)  #square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
np.full([3,3],'asad')

array([['asad', 'asad', 'asad'],
       ['asad', 'asad', 'asad'],
       ['asad', 'asad', 'asad']], dtype='<U4')

In [80]:
np.arange(3,100,5)  # 3 to 100 with 5 increament

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83,
       88, 93, 98])

In [87]:
np.arange(3,100,2).shape

(49,)

In [88]:
np.arange(3,100,2).reshape(7,7)

array([[ 3,  5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53, 55, 57],
       [59, 61, 63, 65, 67, 69, 71],
       [73, 75, 77, 79, 81, 83, 85],
       [87, 89, 91, 93, 95, 97, 99]])

### Random

In [74]:
np.random.rand(4)

array([0.52054869, 0.20985934, 0.24139965, 0.13045406])

In [75]:
np.random.rand(2,3)

array([[0.73904726, 0.69732692, 0.57561508],
       [0.80659128, 0.84241997, 0.89652233]])

In [76]:
np.random.randn(3,3)

array([[-0.7403524 , -1.18430387,  0.91128335],
       [-0.04022116,  2.01268737, -0.12991515],
       [-0.84314384, -1.27084837,  1.29063877]])

In [77]:
np.random

<module 'numpy.random' from '/opt/conda/lib/python3.9/site-packages/numpy/random/__init__.py'>