# Assignment 2 on python


### Numpy Module

Numpy is a module of python.It's full meaning is Numerical Python.It's a library file of many function. 

- numpy.dot
- numpy.sum
- numpy.matmul
- numpy.max
- numpy.mean

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "asad-cuet/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/asad-cuet/numpy-array-operations


'https://jovian.ai/asad-cuet/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [27]:
# List of functions explained 
function1 = np.dot  
function2 = np.sum
function3 = np.matmul
function4 = np.max
function5 = np.mean

## Function 1 - np.dot

Add some explanation about the function in your own words

In [28]:
# Example 1 - working (change this)
arr1 = [1, 2] 
arr2 = [5, 6]
arr1=np.array(arr1)
arr2=np.array(arr2)
np.dot(arr1, arr2)

17

Here we calculated the multiplication of two array

In [29]:
# Example 2 - working
arr1=np.array(arr1)
arr3=np.array([1,2])
print(function1(arr1,arr3))

5


Printed the shape of matrix arr1

In [30]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.dot(arr1, arr2)

array([[21., 24., 27.],
       [47., 54., 61.]])

It result's new array because we didn't converted into numpy array

When calculate dot product we use this function

In [31]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "asad-cuet/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/asad-cuet/numpy-array-operations


'https://jovian.ai/asad-cuet/numpy-array-operations'

## Function 2 - np.shape

We use this function to show the dimension of a matrix

In [33]:
# Example 1 - working
np.sum(arr1)

10.0

sumission of all values of an array

In [34]:
# Example 2 - working
np.sum(arr2)

45

sumission of all values of an array

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
np.sum(arr1,arr2)

TypeError: 'list' object cannot be interpreted as an integer

It breaks beacause there will be only one arguement.To fix it,use one arguement

When we need to sum all the value of array,we use it

In [36]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "asad-cuet/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/asad-cuet/numpy-array-operations


'https://jovian.ai/asad-cuet/numpy-array-operations'

## Function 3 - np.matmul

matmul means matrix multiplication

In [37]:
# Example 1 - working
print(arr1)
print(arr2)
print(np.matmul(arr1,arr2))

[[1, 2], [3, 4.0]]
[[5, 6, 7], [8, 9, 10]]
[[21. 24. 27.]
 [47. 54. 61.]]


Here we calculated matrix multiplication

In [40]:
# Example 2 - working
arr1 @ arr3

array([ 5., 11.])

We can also use @ instead of matmul

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 @ arr3


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

The dimension condition of matrix multiplication is not followed.That's why there is error.To fix it,follow the condition.Match the column number of 1st matrix with row number 2nd matrix

Some closing comments about when to use this function.

In [42]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "asad-cuet/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/asad-cuet/numpy-array-operations


'https://jovian.ai/asad-cuet/numpy-array-operations'

## Function 4 - max

It finds maximum value in a array

In [44]:
# Example 1 - working
print(arr1)

print('max:',np.max(arr1))

[[1, 2], [3, 4.0]]
max: 4.0


We found the maximum value in arr1

In [46]:
# Example 2 - working
print(arr2)

print('Max:',np.max(arr2))

[[5, 6, 7], [8, 9, 10]]
Max: 10


We found the maximum value in arr2

In [47]:
# Example 3 - breaking (to illustrate when it breaks)
np.max(arr1,arr2)

TypeError: 'list' object cannot be interpreted as an integer

This function has only one arguement.But we used 2.That's why occurs error

When we need find maximum value in a array

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "asad-cuet/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/asad-cuet/numpy-array-operations


'https://jovian.ai/asad-cuet/numpy-array-operations'

## Function 5 - np.mean

The mean value is the average value.

In [50]:
# Example 1 - working
speed = [99,86,87,88,86,103,87,94,78,77,85,86]
speed=np.array(speed)
print(np.mean(speed))

88.0


We calculated the mean value of speed

In [52]:
# Example 2 - working
speed.reshape(3,4)
print(np.mean(speed))

88.0


We calculated the mean value of speed

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
np.mean(arr1,arr2)

TypeError: an integer is required (got type list)

It breaks because it has only one arguement.To fix it,remove any arguement

To find the mean value of a array,we use it

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "asad-cuet/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/asad-cuet/numpy-array-operations


'https://jovian.ai/asad-cuet/numpy-array-operations'

## Conclusion

We gathered knowledge about numpy module and we learned to use some important f

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>